version: "3.9"
services:
  betta-website:
    container_name: betta-website
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      HOST: localhost
      PORT: 80
  
  re-mind-backend:
    container_name: re-mind-backend
    depends_on:
      - re-mind-db
    ports:
      - 8080:8080
    env_file:
      - ../.env
      - ../.secure.env
    environment:
      FILE_LOGGING_ENABLED: "false"
      HASHING_SALT: "$2b$11$$A7L3150gijiu5phFV5m78O"
      MONGO_CONNECTION_STRING: mongodb://host.docker.internal:27018/re-mind
      HOST: 0.0.0.0

  re-mind-db:
    container_name: re-mind-db
    image: mongo:6
    ports:
      - 27018:27017