import { useTranslations } from "next-intl";

export default function DialAppPrivacyPolicy() {
	const t = useTranslations("Products.DialApp.privacyPolicy");

	return <div className="Pad">
		<h2>{t("headline")}</h2>
		<p>{t("lastUpdate")}</p>
		<div>
			{/* {t.rich("policy", defaultHtml)} */}
			<p>This Privacy Policy explains how <b>Zentru Systems e.U.</b> ("I", "me", or "my") collects, uses, and protects your personal data when you use my macOS application (the "App") and my associated web checkout services (the "Service").</p>
			<p>I am committed to processing your data in compliance with the General Data Protection Regulation (GDPR) and other applicable data protection laws.</p>
			<hr />
			<br />
			<h3>1. Data Controller</h3>
			<p>For the purpose of the GDPR, the data controller is:</p>
			<p>
				<b>Zentru Systems e.U.</b><br />
				Laurenzgasse 13/11<br />
				Austria<br />
				Email: <a href="mailto:service@zentru.systems">service@zentru.systems</a>
			</p>
			<br />
			<h3>2. Data Stored Locally on Your Device</h3>
			<p>I strongly believe in data minimization. Any data you knowingly create inside the App—including your application settings, preferences, and local configurations—is stored <b>strictly locally on your macOS device</b>.</p>
			<ul>
				<li><p>This data never leaves your machine.</p></li>
				<li><p>I do not operate external application servers, databases, or cloud syncing mechanisms to store your configuration data.</p></li>
			</ul>
			<br />
			<h3>3. Data Collected Externally (RevenueCat Billing & Analytics)</h3>
			<p>The only data collected externally is transaction and performance data managed by my third-party infrastructure partner, <b>RevenueCat, Inc.</b> (which utilizes <b>Stripe, Inc.</b> as the underlying payment gateway). This occurs when you interact with my web checkout or activate premium features.</p>
			<br />
			<h4>A. RevenueCat Billing (Transaction Data)</h4>
			<p>When you subscribe or make a purchase, the following information is processed:</p>
			<ul>
				<li><p><b>Identifiers:</b> Email address (required to generate your receipt and access your billing customer portal) and an alphanumeric App User ID generated by the App.</p></li>
				<li><p><b>Payment Data:</b> Subscription status, purchase history, transaction dates, and country/zip code. <em>Note: Full credit card numbers are handled directly by Stripe and are never visible to or stored by me.</em></p></li>
				<li><p><b>Legal Basis under GDPR:</b> Art. 6(1)(b) GDPR – Performance of a contract (necessary to process your payment and deliver the premium features you purchased).</p></li>
			</ul>
			<br />
			<h4>B. RevenueCat Analytics</h4>
			<p>To ensure system stability, analyze conversion flows, and prevent fraudulent subscription usage, I utilize RevenueCat's analytics tools.</p>
			<ul>
				<li><p><b>Data Processed:</b> Device characteristics (macOS version, hardware model), coarse geographic location derived from IP address (country level), and purchase lifecycle events (e.g., trial starts, renewals, cancellations).</p></li>
				<li><p><b>Legal Basis under GDPR:</b> Art. 6(1)(f) GDPR – Legitimate interests (my operational interest in optimizing my commercial service, debugging product failures, and maintaining app security).</p></li>
			</ul>
			<br />
			<h3>4. Third-Party Data Processors</h3>
			<p>I share the minimum required data with the following processors to operate my billing architecture:</p>
			<ul>
				<li><p><b>RevenueCat, Inc.</b> (Data infrastructure provider located in the USA). Data transfers to the US are secured via standard contractual clauses (SCCs) or verified frameworks approved by the European Commission.</p></li>
				<li><p><b>Stripe, Inc.</b> (Payment gateway provider). Handles direct financial processing under strict PCI-DSS security standards.</p></li>
			</ul>
			<br />
			<h3>5. Data Retention</h3>
			<ul>
				<li><p><b>Local Data:</b> Remains on your device until you delete the App or clean your local application support directories.</p></li>
				<li><p><b>Billing Data:</b> Transaction records stored by RevenueCat are retained as long as your subscription is active, and subsequently archived for the duration required to fulfill local statutory tax, accounting, and legal audit obligations (typically up to 7 years depending on jurisdiction).</p></li>
			</ul>
			<br />
			<h3>6. Your Rights Under the GDPR</h3>
			<p>If you are a resident of the EU/EEA, you possess the following rights regarding your personal data:</p>
			<ul>
				<li><p><b>Right of Access:</b> You can request a copy of the billing data linked to your account.</p></li>
				<li><p><b>Right to Rectification:</b> You can update your billing details via the self-service customer portal.</p></li>
				<li><p><b>Right to Erasure ("Right to be Forgotten"):</b> You can request the deletion of your billing profile, subject to statutory retention limits.</p></li>
				<li><p><b>Right to Data Portability:</b> You can request your transaction data in a structured, machine-readable format.</p></li>
				<li><p><b>Right to Object:</b> You can object to data processing executed under my legitimate interests.</p></li>
			</ul>
			<p>To exercise any of these rights, please contact me at <a href="mailto:service@zentru.systems">service@zentru.systems</a>. You also retain the right to lodge a formal complaint with your local Data Protection Authority.</p>
			<br />
			<h3>7. Changes to This Policy</h3>
			<p>I reserve the right to modify this Privacy Policy at any time. Any changes will be published directly on this page with an updated "Last Updated" timestamp.</p>
		</div>
	</div>
}